version: '2'
services:
    edgeverve-app:
        image: edgeverve
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://edgeverve-mysql:3306/edgeverve?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    edgeverve-mysql:
        extends:
            file: mysql.yml
            service: edgeverve-mysql
